export enum InfoButtons {
  INFO_ABOUT = 'INFO_ABOUT',
  INFO_TIMETABLE = 'INFO_TIMETABLE',
  INFO_PRICE = 'INFO_PRICE',
  INFO_FIRST_TIME = 'INFO_FIRST_TIME',
  INFO_PROMOTIONS = 'INFO_PROMOTIONS',
  INFO_CONTACTS = 'INFO_CONTACTS',
  INFO_QUESTION = 'INFO_QUESTION',
  // INFO_BACK = 'INFO_BACK',
}
