export enum crossfitTypes {
  CROSS_FIT_DAY = 'CROSS_FIT_DAY',
  CROSS_FIT_TIME = 'CROSS_FIT_TIME',
  CROSS_FIT_BOOKING = 'CROSS_FIT_BOOKING',
  CROSS_FIT_CANCEL = 'CROSS_FIT_CANCEL',
  CROSS_FIT_TIME_BACK = 'CROSS_FIT_TIME_BACK',
  CROSS_FIT_DAY_BACK = 'CROSS_FIT_DAY_BACK',
  CROSS_FIT_MY_BACK = 'CROSS_FIT_MY_BACK',
}
